name: PR Environment Print

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variable
        run: echo "Environment Variable ${{ env.MY_ENV_VAR }}"
        env:
          MY_ENV_VAR: "This is a sample environment variable"

      - name: Print secret
        run: echo "Secret ${{ secrets.SECRET }}"

      
